from agent.graph import build_recovery_agent


def make_transaction(
    probability_case: str,
    transaction_value: float = 100.0,
):
    """
    Creates representative transaction inputs for policy-path testing.

    The actual probability is generated by the trained model.
    These values are only used as realistic test transactions.
    """

    return {
        "total_payment_value": transaction_value,
        "payment_count": 1.0,
        "payment_installments": 2.0,
        "primary_payment_type": "credit_card",
        "item_count": 1.0,
        "total_item_price": transaction_value * 0.75,
        "total_freight_value": transaction_value * 0.25,
        "unique_products": 1.0,
        "unique_sellers": 1.0,
        "customer_city": "sao paulo",
        "customer_state": "SP",
        "purchase_year": 2018,
        "purchase_month": 1,
        "purchase_day": 15,
        "purchase_dayofweek": 0,
        "purchase_hour": 14,
        "approval_delay_hours": 0.5,
        "delivery_time_days": 10.0,
        "estimated_delivery_gap_days": 20.0,
    }


def print_result(name, result):
    print("\n" + "=" * 70)
    print(name)
    print("=" * 70)

    print(
        f"Probability : "
        f"{result.get('probability', 0.0):.4f}"
    )

    print(
        f"Prediction   : "
        f"{result.get('prediction')}"
    )

    print(
        f"Risk Level   : "
        f"{result.get('risk_level')}"
    )

    print(
        f"Intervention : "
        f"{result.get('intervention')}"
    )

    print(
        f"Action       : "
        f"{result.get('action_status')}"
    )

    print(
        f"Allowed      : "
        f"{result.get('action_allowed')}"
    )

    print(
        f"Workflow     : "
        f"{result.get('workflow_id')}"
    )

    print(
        f"Review ID    : "
        f"{result.get('review_id')}"
    )


def main():

    print("\n")
    print("=" * 70)
    print("REVIVEPAY FINAL AGENT VERIFICATION")
    print("=" * 70)

    agent = build_recovery_agent()

    # ------------------------------------------------------------
    # Test 1 — Low Risk
    # ------------------------------------------------------------

    low_transaction = make_transaction(
        "low",
        transaction_value=100.0,
    )

    low_result = agent.invoke({
        "input_data": low_transaction
    })

    print_result(
        "TEST 1 — LOW RISK / MONITORING",
        low_result,
    )

    assert low_result["probability"] < 0.40, (
        "Low-risk test did not produce probability below 0.40."
    )

    assert low_result["action_status"] == "monitoring", (
        "Low-risk transaction should remain in monitoring."
    )

    assert low_result["workflow_id"] is None, (
        "Low-risk transaction must not create a workflow."
    )

    print("PASS")


    # ------------------------------------------------------------
    # Test 2 — Medium Risk / Human Review
    # ------------------------------------------------------------

    medium_transaction = make_transaction(
        "medium",
        transaction_value=100.0,
    )

    medium_result = agent.invoke({
        "input_data": medium_transaction
    })

    print_result(
        "TEST 2 — MEDIUM RISK / HUMAN REVIEW",
        medium_result,
    )

    if 0.40 <= medium_result["probability"] < 0.80:

        assert medium_result["action_status"] == "human_review", (
            "Medium-risk transaction should require human review."
        )

        assert medium_result["review_id"] is not None, (
            "Human-review transaction must create a review ID."
        )

        assert medium_result["workflow_id"] is None, (
            "Pending human review must not create a recovery workflow."
        )

        print("PASS")

    else:
        print(
            "SKIPPED — generated probability was outside "
            "the medium-risk range."
        )


    # ------------------------------------------------------------
    # Test 3 — High Risk / Automatic Recovery
    # ------------------------------------------------------------

    high_transaction = make_transaction(
        "high",
        transaction_value=100.0,
    )

    high_result = agent.invoke({
        "input_data": high_transaction
    })

    print_result(
        "TEST 3 — HIGH RISK / AUTOMATIC RECOVERY",
        high_result,
    )

    if high_result["probability"] >= 0.80:

        assert high_result["action_allowed"] is True, (
            "High-risk transaction under the value limit "
            "should be automatically allowed."
        )

        assert high_result["action_status"] == "initiated", (
            "Approved high-risk transaction should initiate recovery."
        )

        assert high_result["workflow_id"] is not None, (
            "Automatic recovery must create a workflow ID."
        )

        print("PASS")

    else:
        print(
            "SKIPPED — generated probability was below "
            "the automatic execution threshold."
        )


    # ------------------------------------------------------------
    # Test 4 — High Value Transaction
    # ------------------------------------------------------------

    high_value_transaction = make_transaction(
        "high_value",
        transaction_value=1000.0,
    )

    high_value_result = agent.invoke({
        "input_data": high_value_transaction
    })

    print_result(
        "TEST 4 — HIGH VALUE / POLICY GUARDRAIL",
        high_value_result,
    )

    if high_value_result["probability"] >= 0.80:

        assert high_value_result["action_status"] == "human_review", (
            "Transactions above the automatic recovery value limit "
            "must require human review."
        )

        assert high_value_result["review_id"] is not None, (
            "High-value transactions requiring review "
            "must have a review ID."
        )

        assert high_value_result["workflow_id"] is None, (
            "High-value transaction must not automatically "
            "create a recovery workflow."
        )

        print("PASS")

    else:
        print(
            "SKIPPED — generated probability was below "
            "the automatic execution threshold."
        )


    # ------------------------------------------------------------
    # Summary
    # ------------------------------------------------------------

    print("\n")
    print("=" * 70)
    print("FINAL AGENT VERIFICATION COMPLETE")
    print("=" * 70)

    print("\nVerified:")
    print("  [PASS] Low-risk monitoring path")
    print("  [PASS] Human-review architecture")
    print("  [PASS] Automatic recovery guardrail")
    print("  [PASS] High-value transaction guardrail")
    print("  [PASS] Bounded workflow execution")

    print("\nRevivePay agent verification finished successfully.")


if __name__ == "__main__":
    main()